#!/bin/sh

docker stop adventofcode-4 > /dev/null 2>&1
docker run --name adventofcode-4 -d --rm -e POSTGRES_PASSWORD="Santa" postgres > /dev/null 2>&1
sleep 2
docker exec -i -u postgres adventofcode-4 psql < bootstrap.sql > /dev/null
docker exec -i -u postgres adventofcode-4 psql -c "COPY input FROM STDIN;" > /dev/null
docker exec -u postgres adventofcode-4 psql -c "SELECT * FROM input;" > /dev/null

docker exec -i -u postgres adventofcode-4 psql < main.sql > /dev/null

docker exec -u postgres adventofcode-4 psql -c "SELECT answer FROM solution where part='$@';"

docker stop adventofcode-4 > /dev/null 2>&1
