name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: ./2019
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./2019
    - name: Get Code Coverage
      uses: actions-rs/grcov@v0.1.4
